version: '3.8'

services:
  db:
    image: mysql:8
    container_name: food_order_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_order_system
      MYSQL_USER: turing
      MYSQL_PASSWORD: turing
    ports:
      - '9800:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
